PCMS/PCMS/PCMS/Areas/MasterData/Controllers/md_masterData_CustomerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PCMS.Areas.MasterData.Models;
using PagedList;
using PCMS.Models;
using PCMS.Helper;

namespace PCMS.Areas.MasterData.Controllers
{
    [LogActionFilter]
    [Authorize]
    public class md_masterData_CustomerController : Controller
    {
        public bool checkTrader = true;
        public bool checkRate = true;
        private MasterDataContext db = new MasterDataContext();

        // GET: MasterData/md_masterData_Customer
        public ActionResult Index(PaginationModel pg)
        {
            var model = db.Md_masterData_Customer.Include(m=>m.Md_masterData_Contact).Include(m=>m.Md_masterData_Address).Where(m => m.IsActive == true && m.IsDeleted == false).OrderBy(a => a.Id).ToList();

            if (pg != null)
            {
                foreach (PaginationFulltextFilter pgFF in pg.pagFulFilter)
                {
                    if (!string.IsNullOrWhiteSpace(pgFF.colVal))
                    {
                        pgFF.colVal = pgFF.colVal.ToLower();
                        switch (pgFF.colName)
                        {
                            case "CustomerId":
                                model = model.Where(m => m.CustomerId.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.FilterCity = pgFF.colVal;
                                break;
                            case "Name":
                                model = model.Where(m => m.Name.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.FilterCity = pgFF.colVal;
                                break;
                            case "Street":
                                model = model.Where(m => m.Md_masterData_Address!=null && m.Md_masterData_Address.Street != null && m.Md_masterData_Address.Street.ToLower().Contains(pgFF.colVal)).ToList();
                                ViewBag.FilterCity = pgFF.colVal;
                                break;
                            case "ZipCode":
                                model = model.Where(m => m.Md_masterData_Address.ZipCode != null && m.Md_masterData_Address.ZipCode.ToLower().Contains(pgFF.colVal)).ToList();
                                break;
                            case "City":
                                model = model.Where(m => m.Md_masterData_Address!= null && m.Md_masterData_Address.City != null && m.Md_masterData_Address.City.ToLower().Contains(pgFF.colVal)).ToList();
                                break;
                        }
                    }
                }

            }
            switch (pg.orderCol)
            {
                case "CustomerId":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.CustomerId).ToList();
                    else
                        model = model.OrderByDescending(m => m.CustomerId).ToList();
                    break;
                case "Name":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Name).ToList();
                    else
                        model = model.OrderByDescending(m => m.Name).ToList();
                    break;
                case "Street":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Md_masterData_Address.Street).ToList();
                    else
                        model = model.OrderByDescending(m => m.Md_masterData_Address.Street).ToList();
                    break;
                case "ZipCode":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Md_masterData_Address.ZipCode).ToList();
                    else
                        model = model.OrderByDescending(m => m.Md_masterData_Address.ZipCode).ToList();
                    break;
                case "City":
                    if (pg.orderDir.Equals("desc"))
                        model = model.OrderBy(m => m.Md_masterData_Address.City).ToList();
                    else
                        model = model.OrderByDescending(m => m.Md_masterData_Address.City).ToList();
                    break;
            }

            return View(model.ToPagedList((pg.page ?? 1), pg.pageSize ?? Helper.Definitions.pageSize));
        }

        // Get
        public ActionResult Create()
        {
            ViewBag.Number = db.Md_material_Config.Where(a => a.Id == 1).Select(a => a.CustomerNumber).FirstOrDefault();
            return View();
        }

        // Post
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(MasterDataContactView model)
        {
            if(!String.IsNullOrEmpty(model.customer.TraderId))
            {
                if (db.Md_masterData_Trader.Any(m => m.TraderId == model.customer.TraderId) == false)
                {
                    checkTrader = false;
                }
                else
                {
                    checkTrader = true;
                }
            }

            if(!String.IsNullOrEmpty(model.custRating.Description))
            {
                if(db.Md_masterData_CustomerRating.Any(m => m.Description == model.custRating.Description) == false)
                {
                    checkRate = false;
                }
                else
                {
                    checkRate = true;
                }
            }

            if (ModelState.IsValid && checkTrader == true && checkRate == true)
            {
                model.customer.IsActive = true;
                model.customer.IsDeleted = false;

                db.Md_masterData_Address.Add(model.address);
                if (db.Md_masterData_Address.Add(model.address) != null)
                {
                    db.SaveChanges();
                }
                db.Md_masterData_Contact.Add(model.contact);
                if (db.Md_masterData_Contact.Add(model.contact) != null)
                {
                    db.SaveChanges();
                }

                model.customer.AddressId = model.address.Id;
                model.customer.ContactId = model.contact.Id;
                db.Md_masterData_Customer.Add(model.customer);
                
                db.SaveChanges();
        
                try
                {
                    var CustomerNumber = Convert.ToInt64(db.Md_material_Config.Where(a => a.Id == 1).Select(a => a.CustomerNumber).FirstOrDefault());
                    CustomerNumber = CustomerNumber+1;
                    string query = "UPDATE md_Config SET CustomerNumber = " + CustomerNumber.ToString() + " WHERE Id = 1";
                    db.Database.ExecuteSqlCommand(query);
                }
                catch
                {

                }
                
                return RedirectToAction("Index");
            }
            else
            {
                ModelState.AddModelError("Fehler", "Fehlermeldung");
                return View();
            }
        }

        public ActionResult Edit(MasterDataContactView model, long? id)
        {
            if (ModelState.IsValid)
            {
                if (id == null)
                {
                    return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
                }

                if (db.Md_masterData_Customer.Find(id) == null)
                {
                    return HttpNotFound();
                }

                model.customer = db.Md_masterData_Customer.Find(id);
                model.address = db.Md_masterData_Address.Find(model.customer.AddressId);
                model.contact = db.Md_masterData_Contact.Find(model.customer.ContactId);
                model.custRating = db.Md_masterData_CustomerRating.Find(model.customer.CustomerRatingId);

                return View(model);
            }

            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(MasterDataContactView model)
        {

            if (!String.IsNullOrEmpty(model.customer.TraderId))
            {
                if (db.Md_masterData_Trader.Any(m => m.TraderId == model.customer.TraderId) == false)
                {
                    checkTrader = false;
                }
                else
                {
                    checkTrader = true;
                }
            }

            if (!String.IsNullOrEmpty(model.custRating.Description))
            {
                if (db.Md_masterData_CustomerRating.Any(m => m.Description == model.custRating.Description) == false)
                {
                    checkRate = false;
                }
                else
                {
                    checkRate = true;
                }
            }

            if (checkTrader == true && checkRate == true)
            {
                model.customer.IsActive = true;
                model.customer.IsDeleted = false;
                //Änderung Manu 2016_03_09
                if (model.contact.Id == null)
                {
                    db.Entry(model.contact).State = EntityState.Added;
                    db.SaveChanges();
                    model.customer.ContactId = model.contact.Id;
                }
                else
                    db.Entry(model.contact).State = EntityState.Modified;

                db.Entry(model.customer).State = EntityState.Modified;
                db.Entry(model.address).State = EntityState.Modified;

                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(model);
        }

        // GET
        public ActionResult Delete(MasterDataContactView model, long? id)
        {
            if (id == null)
            {

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_Customer/ChooseRating.cshtml
@model List<PCMS.Areas.MasterData.Models.md_masterData_CustomerRating>
@using PagedList.Mvc

<div class="tableContent" tablename="md_masterData_CustomRating">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    @{
        ViewBag.Title = "Bonitäts Auswahl";
        Layout = "~/Views/Shared/_Layout.cshtml";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }

    <div style="overflow-x: auto;">
        <table class="table table-hover table-condensed" tablename="md_masterData_CustomRating">
            <thead>
                <tr class="caption">
                    <th editable="false" colname="Id" style="">@Html.DisplayNameFor(model => model[0].Id)</th>
                    <th editable="true" colname="Description" style="">@Html.DisplayNameFor(model => model[0].Description)</th>
                    <th editable="true" colname="Comment" style="">@Html.DisplayNameFor(model => model[0].Comment)</th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id" onclick="chooseRa(this)">
                        <td columnname="Id" style="" tablename="md_masterData_CustomRating">@Html.DisplayFor(modelItem => item.Id)</td>
                        <td columnname="Description" style="" tablename="md_masterData_CustomRating">@Html.DisplayFor(modelItem => item.Description)</td>
                        <td columnname="Comment" style="" tablename="md_masterData_CustomRating">@Html.DisplayFor(modelItem => item.Comment)<td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<script>
        function chooseRa(e) {
            $("#custRating_Description").val($(e).closest("tr").find("td[columnname='Description']").text().trim());
            $("#rId input").val($(e).closest("tr").find("td[columnname='Id']").text().trim());
            $("#ModalChild").modal("hide");
        }
</script>

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_Customer/ChooseTrader.cshtml
@model PagedList.IPagedList<PCMS.Areas.MasterData.Models.md_masterData_Trader>
@using PagedList.Mvc

<div class="tableContent" tablename="md_masterData_Trader">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    @{
        ViewBag.Title = "Händlernummer Auswahl";
        Layout = "~/Views/Shared/_Layout.cshtml";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }
    @Html.AntiForgeryToken()
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
    <div style="overflow-x: auto;">
        <table url="@Url.Action("ChooseTrader","md_masterData_Customer", new { area = "MasterData" } )" class="table table-hover table-condensed" tablename="md_masterData_Trader">
            <thead>
                <tr class="caption">
                    <th editable="false" colname="Id" style="display:none">@Html.DisplayNameFor(model => model[0].Id)</th>
                    <th editable="true" colname="Name" style="">@Html.DisplayNameFor(model => model[0].Name)</th>
                    <th editable="true" colname="TraderId" style="">@Html.DisplayNameFor(model => model[0].TraderId)</th>
                    <th editable="true" colname="Street" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.Street)</th>
                    <th editable="true" colname="ZipCode" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.ZipCode)</th>
                    <th editable="true" colname="City" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.City)</th>
                </tr>
                <tr>
                    <th style="display:none" class="head-filter" columnname="Id" tablename="md_masterData_Trader"></th>
                    <th style="" class="head-filter" columnname="Name" tablename="md_masterData_Trader"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(this)" type="text" placeholder="Suchen"/></th>
                    <th style="" class="head-filter" columnname="TraderId" tablename="md_masterData_Trader"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(this)" type="text" placeholder="Suchen"/></th>
                    <th style="" class="head-filter" columnname="Street" tablename="md_masterData_Trader"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(this)" type="text" placeholder="Suchen"/></th>
                    <th style="" class="head-filter" columnname="ZipCode" tablename="md_masterData_Trader"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(this)" type="text" placeholder="Suchen" /></th>
                    <th style="" class="head-filter" columnname="City" tablename="md_masterData_Trader"><input class="head-filter-value form-control" onkeydown="headFilterKeyDownModal(this)" type="text" placeholder="Suchen" /></th>
                </tr>
            </thead>

            <tbody>
                @foreach (var item in Model)
                {
                    <tr id="@item.Id" onclick="chooseTr(this)">
                        <td columnname="Id" style="display:none" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.Id)</td>
                        <td columnname="Name" style="" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.Name)</td>
                        <td columnname="TraderId" style="" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.TraderId)</td>
                        <td columnname="Street" style="" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.Md_masterData_Address.Street)</td>
                        <td columnname="ZipCode" style="" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.Md_masterData_Address.ZipCode)</td>
                        <td columnname="City" style="" tablename="md_masterData_Trader">@Html.DisplayFor(modelItem => item.Md_masterData_Address.City)</td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Paging.cshtml", Model)
</div>

<script>
    function chooseTr(e) {
        $("#customer_TraderId").val($(e).closest("tr").find("td[columnname='TraderId']").text().trim());
        $("#ModalChild").modal("hide");
    }
</script>

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_Customer/ConstructionSiteIndex.cshtml
@model List<PCMS.Areas.MasterData.Models.md_masterData_ConstructionSite>

<div class="tableContent" tablename="md_masterData_Trader">
    <link href="~/Content/PagedList.css" rel="stylesheet" type="text/css" />

    @{
        ViewBag.Title = "Baustelle";
        if (Request.IsAjaxRequest())
        {
            Layout = null;
        }
    }
    <div style="overflow-x: auto;">
        @*<table class="table table-hover table-condensed" tablename="md_masterData_CustomerConstructionSite" markUrl="@Url.Action("MarkConstructionSite", "md_masterData_Customer", new { area = "masterData" })" deleteUrl="@Url.Action("DeleteConstructionSite", "md_masterData_Customer", new { area = "masterData" })">*@
        <table class="table table-hover table-condensed" tablename="md_masterData_CustomerConstructionSite">
            <thead>
                <tr class="caption">
                    <th editable="false" colname="ConstructionSiteNumber" style="">@Html.DisplayNameFor(model => model[0].ConstructionSiteId)</th>
                    <th editable="true" colname="Name" style="">@Html.DisplayNameFor(model => model[0].Name)</th>
                    <th editable="true" colname="Street" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.Street)</th>
                    <th editable="true" colname="ZipCode" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.ZipCode)</th>
                    <th editable="true" colname="City" style="">@Html.DisplayNameFor(model => model[0].Md_masterData_Address.City)</th>
                </tr>
            </thead>

            <tbody id="body">
                @foreach (var item in Model)
                {
                <tr id="@item.Id">
                    <td id="Id" columnname="Id" style="display:none" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.Id)</td>
                    <td id="Number" columnname="ConstructionSiteNumber" style="" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.ConstructionSiteId)</td>
                    <td id="Name" columnname="Name" style="" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.Name)</td>
                    <td columnname="Street" style="" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.Md_masterData_Address.Street)</td>
                    <td columnname="ZipCode" style="" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.Md_masterData_Address.ZipCode)</td>
                    <td columnname="City" style="" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.Md_masterData_Address.City)</td>
                    <td columnname="IsActive" style="display:none" tablename="md_masterData_Customer_ConstractionSite">@Html.DisplayFor(modelItem => item.IsActive)</td>
                </tr>
                }
            </tbody>
        </table>
    </div>
</div>
<script>
    $(document).ready(function () {
        $('#body tr').filter(':has(:checkbox:not(:checked))').find('td').each(function () {
            var this_row = $(this);
            this_row.css('background-color', 'orange');
        });
    });

    $('#body tr').click(function () {
        var ConstNo = $(this).closest('tr').find('#Id').text();
        var ConstName = $(this).closest('tr').find('#Name').text();
        alert("Die Baustelle ''" + ConstName + "'' wirklich deaktivieren?");
        var row = $(this).closest('tr');
        $.ajax({
            url: "/MasterData/md_masterData_Customer/MarkConstructionSiteConfirmed",
            data: { id: ConstNo }
        }).done(function (data) {
            if (data) {
                row.css('background-color', 'orange');
            }
            else {
                alert("Baustelle konnte nicht markiert werden!");
            }
        });      
    });
</script>

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_Customer/Create.cshtml
@model PCMS.Areas.MasterData.Models.MasterDataContactView
@{
    ViewBag.Title = "Kunden erstellen";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div id="rId">@Html.HiddenFor(model => model.customer.CustomerRatingId)</div>

    @Html.Partial("~/Views/Shared/Partial_Cancel_Save_t.cshtml")

    <div class="row">
        <div class="col-md-12" style="background-color:lightgrey"><h3>Kundendaten</h3></div>
    </div>
    <div><br /></div>

    <div class="row">
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.customer.Name, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.customer.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.customer.Name)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.customer.CustomerId, htmlAttributes: new { @class = "control-label"})
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.customer.CustomerId, new { htmlAttributes = new { @class = "form-control", @Value = ViewBag.Number } })
                @Html.ValidationMessageFor(model => model.customer.CustomerId)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.customer.CustomerIdEDV, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2" >
            <div class="editor-field">
                @Html.EditorFor(model => model.customer.CustomerIdEDV, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.customer.CustomerIdEDV)
            </div>
        </div>
    </div>

    <div class="col-md-12"><hr /></div>

    <div class="row">
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.address.Street, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.address.Street, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address.Street)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.address.ZipCode, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.address.ZipCode, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address.ZipCode)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.address.City, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.address.City, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.address.City)
            </div>
        </div>
    </div>

    <div class="col-md-12"><hr /></div>

    <div class="row">
        <div class="col-md-2 col-md-offset-1">
            <input type="button" class="btn btn-default" value="Händler auswählen" style="width:240px;" onclick="openModalChild('@Url.Action("ChooseTrader","md_masterData_Customer", new { area = "MasterData" } )', Title = 'Händler auswählen')" />
        </div>
        <div class="col-md-2 col-md-offset-1">
            <input type="button" class="btn btn-default" value="Bonität auswählen" style="width:240px;" onclick="openModalChild('@Url.Action("chooseRating","md_masterData_Customer", new { area = "MasterData" } )', Title = 'Bonität auswählen')" />
        </div>
    </div>
    <div><br /></div>
    <div class="row">
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.customer.TraderId, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.customer.TraderId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.customer.TraderId)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.custRating.Description, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.custRating.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.custRating.Description)
            </div>
        </div>
    </div>
    <div class="col-md-12"><hr /></div>

    <div class="row">
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.customer.Discount, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.customer.Discount, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.customer.Discount)
            </div>
        </div>
    </div>
    <div class="col-md-12"><hr /></div>

    <div class="row">
        <div class="col-md-12" style="background-color:lightgrey"><h3>Ansprechpartner</h3></div>
    </div>
    <div><br /></div>

    <div class="row">
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.contact.FirstName, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.contact.FirstName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact.FirstName)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.contact.LastName, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.contact.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact.LastName)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.contact.Tel, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.contact.Tel, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact.Tel)
            </div>
        </div>
        <div class="col-md-1">
            <div class="editor-label">
                @Html.LabelFor(model => model.contact.Mobile, htmlAttributes: new { @class = "control-label" })
            </div>
        </div>
        <div class="col-md-2">
            <div class="editor-field">
                @Html.EditorFor(model => model.contact.Mobile, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.contact.Mobile)
            </div>
        </div>
    </div>
    @Html.Partial("~/Views/Shared/Partial_Cancel_Save_b.cshtml")
}
<script>
    function openModalChild(url, titel) {
        var _url = "./MenuElementCreate";
        if (url) {
            _url = url;
        }
        $.ajax({

            url: _url,
            type: "GET",
            dataType: "text",
            //contentType: 'application/json',
            success: function (data) {
                chooseModalChild(titel, data, ["", ""]);
            }
        });
    }

    function chooseModalChild(titel, content, arg) {
        var modal = "";
        modal += '<div id="ModalChild" class="modal fade">';
        modal += '<div class="modal-dialog">';
        modal += '<div class="modal-content">';
        modal += '<div class="modal-header">';
        modal += '<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>';
        modal += '<h4 class="modal-title">' + titel + '</h4>';
        modal += '</div>';
        modal += '<div class="modal-body">';
        modal += '<p>' + content + '</p>';
        modal += '</div>';
        modal += '</div>';
        modal += '</div>';
        modal += '</div>';
        modal += '</div>';
        var dModal = $(modal);
        dModal.modal('show');

        $(dModal).on('hidden.bs.modal', function (e) {
            $(this).remove();
        })
    }

    $("#address_ZipCode").blur(function(){
        $.post("/MasterData/md_masterData_Customer/SearchCity", { zip: $("#address_ZipCode").val() }, function (data) {
            $("#address_City").val(data.City);
        });
    });

    $("#address_City").blur(function(){
        $.post("/MasterData/md_masterData_Customer/SearchZip", { city: $("#address_City").val() }, function (data) {
            $("#address_ZipCode").val(data.Zip);
        });
    });
</script>

PCMS/PCMS/PCMS/Areas/MasterData/Views/md_masterData_Customer/DeleteConstructionSite.cshtml
@model PCMS.Areas.MasterData.Models.MasterDataContactView
@{
    ViewBag.Title = "Baustelle löschen?";
    Layout = "~/Views/Shared/_Layout.cshtml";
    if (Request.IsAjaxRequest())
    {
        Layout = null;
    }
}


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

   @Html.HiddenFor(model=>model.constructionSite.Id)

    <div>Möchten sie den Kunden "@Html.DisplayTextFor(model => model.constructionSite.Name)" wirklich löschen?</div>
    <div><hr /></div>
    <div class="form-actions no-color">
        <input type="button" onclick="location.href=''" value="Zurück zur Liste" class="btn btn-default" /> |
        <input type="submit" value="Löschen" class="btn btn-default" />
    </div>
}